version: '3'

services: 
    python-api:
        build: .
        container_name: python-api
        command: flask run --host=0.0.0.0
        volumes:
            - ./:/app
        expose:
            - "5000"
        ports:
            - 5000:5000
    python-mongodb:
        image: mongo:3.4
        container_name: python-mongo-container
        ports:
            - "27108:27017"
        volumes:
            - pythonmongodata:/var/lib/mongodb
volumes:
    pythonmongodata:
        external: true
